' Array Creator
' Author: Ian P [ippavlin]

Imports System.IO

Public Class InputFile
    Private Sub cmdCreateArray_Click(sender As System.Object, e As System.EventArgs) Handles cmdCreateArray.Click
        Dim ioFile As String = txtSrcFile.Text

        If File.Exists(ioFile) And txtArrayName.Text <> Nothing Then
            Try
                Dim wordlist As New List(Of String)
                Dim reader As New StreamReader(ioFile)
                Do While reader.Peek <> -1
                    wordlist.Add(reader.ReadLine())
                Loop
                reader.Close()

                Dim w As StreamWriter
                w = New StreamWriter(Path.GetFileNameWithoutExtension(ioFile) & "_array.txt")
                w.WriteLine("' This file has automatically been generated by Ian's ArrayWriter.")
                w.WriteLine("")
                w.WriteLine("' -------------------------  BEGIN CODE  -------------------------")
                w.WriteLine("")
                w.WriteLine("Dim " & txtArrayName.Text & "(" & wordlist.Count - 1 & ") As String")
                w.WriteLine("")
                For i = 0 To wordlist.Count - 1
                    w.WriteLine(txtArrayName.Text & "(" & i & ") = """ & wordlist.Item(i) & """")
                Next
                w.WriteLine("")
                w.WriteLine("' --------------------------  END CODE  --------------------------")
                w.Close()

                Process.Start(Path.GetFileNameWithoutExtension(ioFile) & "_array.txt")
                MessageBox.Show(wordlist.Count & " words were converted to an array in " & Path.GetFileNameWithoutExtension(ioFile) & "_array.txt", "Success!")
            Catch ex As Exception
                MessageBox.Show(ex.Message, "Error")
            End Try
        Else
            MessageBox.Show("File does not exist: " & ioFile, "Error")
        End If
    End Sub

    Private Sub txtSrcFile_MouseDoubleClick(sender As Object, e As System.Windows.Forms.MouseEventArgs) Handles txtSrcFile.MouseDoubleClick
        Dim OpenWindow As New OpenFileDialog

        With OpenWindow
            'Some default settings we want to add.
            .Filter = "Rich-text Files (*.rtf)|*.rtf|Text Files (*.txt)|*.txt"  'Shown formats
            .FilterIndex = 2    'Default file format choice; in this case .txt
            .Multiselect = False    'We don't really have a way to handle multi-file selections so disable it.
        End With

        If OpenWindow.ShowDialog() = DialogResult.OK Then
            txtSrcFile.Text = OpenWindow.FileName
        End If
    End Sub

    Private Sub InputFile_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load

    End Sub
End Class
